[package]
name = "ferrish"
version = "0.1.0"
authors = ["Carson Price <cdprice02@users.noreply.github.com>"]
edition = "2024"
rust-version = "1.91"

[dependencies]
anyhow = "1.0.68"
bytes = "1.3.0"
is_executable = "1.0.5"
strum = { version = "0.27.2", features = ["derive"] }
thiserror = "1.0.38"
